CREATE TABLE [dbo].[BlitzCache] (
    [ID]                            BIGINT             IDENTITY (1, 1) NOT NULL,
    [ServerName]                    NVARCHAR (258)     NULL,
    [CheckDate]                     DATETIMEOFFSET (7) NULL,
    [Version]                       NVARCHAR (258)     NULL,
    [QueryType]                     NVARCHAR (258)     NULL,
    [Warnings]                      VARCHAR (MAX)      NULL,
    [DatabaseName]                  [sysname]          NOT NULL,
    [SerialDesiredMemory]           FLOAT (53)         NULL,
    [SerialRequiredMemory]          FLOAT (53)         NULL,
    [AverageCPU]                    BIGINT             NULL,
    [TotalCPU]                      BIGINT             NULL,
    [PercentCPUByType]              MONEY              NULL,
    [CPUWeight]                     MONEY              NULL,
    [AverageDuration]               BIGINT             NULL,
    [TotalDuration]                 BIGINT             NULL,
    [DurationWeight]                MONEY              NULL,
    [PercentDurationByType]         MONEY              NULL,
    [AverageReads]                  BIGINT             NULL,
    [TotalReads]                    BIGINT             NULL,
    [ReadWeight]                    MONEY              NULL,
    [PercentReadsByType]            MONEY              NULL,
    [AverageWrites]                 BIGINT             NULL,
    [TotalWrites]                   BIGINT             NULL,
    [WriteWeight]                   MONEY              NULL,
    [PercentWritesByType]           MONEY              NULL,
    [ExecutionCount]                BIGINT             NULL,
    [ExecutionWeight]               MONEY              NULL,
    [PercentExecutionsByType]       MONEY              NULL,
    [ExecutionsPerMinute]           MONEY              NULL,
    [PlanCreationTime]              DATETIME           NULL,
    [PlanCreationTimeHours]         AS                 (datediff(hour,CONVERT([datetimeoffset](7),[PlanCreationTime]),[CheckDate])),
    [LastExecutionTime]             DATETIME           NULL,
    [LastCompletionTime]            DATETIME           NULL,
    [PlanHandle]                    VARBINARY (64)     NULL,
    [Remove Plan Handle From Cache] AS                 (case when [PlanHandle] IS NOT NULL then ('DBCC FREEPROCCACHE ('+CONVERT([varchar](128),[PlanHandle],(1)))+');' else 'N/A' end),
    [SqlHandle]                     VARBINARY (64)     NULL,
    [Remove SQL Handle From Cache]  AS                 (case when [SqlHandle] IS NOT NULL then ('DBCC FREEPROCCACHE ('+CONVERT([varchar](128),[SqlHandle],(1)))+');' else 'N/A' end),
    [SQL Handle More Info]          AS                 (case when [SqlHandle] IS NOT NULL then ('EXEC sp_BlitzCache @OnlySqlHandles = '''+CONVERT([varchar](128),[SqlHandle],(1)))+'''; ' else 'N/A' end),
    [QueryHash]                     BINARY (8)         NULL,
    [Query Hash More Info]          AS                 (case when [QueryHash] IS NOT NULL then ('EXEC sp_BlitzCache @OnlyQueryHashes = '''+CONVERT([varchar](32),[QueryHash],(1)))+'''; ' else 'N/A' end),
    [QueryPlanHash]                 BINARY (8)         NULL,
    [StatementStartOffset]          INT                NULL,
    [StatementEndOffset]            INT                NULL,
    [PlanGenerationNum]             BIGINT             NULL,
    [MinReturnedRows]               BIGINT             NULL,
    [MaxReturnedRows]               BIGINT             NULL,
    [AverageReturnedRows]           MONEY              NULL,
    [TotalReturnedRows]             BIGINT             NULL,
    [QueryText]                     NVARCHAR (MAX)     NULL,
    [QueryPlan]                     XML                NULL,
    [NumberOfPlans]                 INT                NULL,
    [NumberOfDistinctPlans]         INT                NULL,
    [MinGrantKB]                    BIGINT             NULL,
    [MaxGrantKB]                    BIGINT             NULL,
    [MinUsedGrantKB]                BIGINT             NULL,
    [MaxUsedGrantKB]                BIGINT             NULL,
    [PercentMemoryGrantUsed]        MONEY              NULL,
    [AvgMaxMemoryGrant]             MONEY              NULL,
    [MinSpills]                     BIGINT             NULL,
    [MaxSpills]                     BIGINT             NULL,
    [TotalSpills]                   BIGINT             NULL,
    [AvgSpills]                     MONEY              NULL,
    [QueryPlanCost]                 FLOAT (53)         NULL,
    [JoinKey]                       AS                 ([ServerName]+CONVERT([nvarchar](50),[CheckDate])),
    CONSTRAINT [PK_BlitzCache] PRIMARY KEY CLUSTERED ([ID] ASC)
);

