CREATE TABLE [dbo].[BlitzWho] (
    [ID]                                      INT                IDENTITY (1, 1) NOT NULL,
    [ServerName]                              NVARCHAR (128)     NOT NULL,
    [CheckDate]                               DATETIMEOFFSET (7) NOT NULL,
    [elapsed_time]                            VARCHAR (41)       NULL,
    [session_id]                              SMALLINT           NOT NULL,
    [database_name]                           NVARCHAR (128)     NULL,
    [query_text]                              NVARCHAR (MAX)     NULL,
    [outer_command]                           NVARCHAR (4000)    NULL,
    [query_plan]                              XML                NULL,
    [live_query_plan]                         XML                NULL,
    [cached_parameter_info]                   NVARCHAR (MAX)     NULL,
    [live_parameter_info]                     NVARCHAR (MAX)     NULL,
    [query_cost]                              FLOAT (53)         NULL,
    [status]                                  NVARCHAR (30)      NOT NULL,
    [wait_info]                               NVARCHAR (MAX)     NULL,
    [wait_resource]                           NVARCHAR (MAX)     NULL,
    [top_session_waits]                       NVARCHAR (MAX)     NULL,
    [blocking_session_id]                     SMALLINT           NULL,
    [open_transaction_count]                  INT                NULL,
    [is_implicit_transaction]                 INT                NOT NULL,
    [nt_domain]                               NVARCHAR (128)     NULL,
    [host_name]                               NVARCHAR (128)     NULL,
    [login_name]                              NVARCHAR (128)     NOT NULL,
    [nt_user_name]                            NVARCHAR (128)     NULL,
    [program_name]                            NVARCHAR (128)     NULL,
    [fix_parameter_sniffing]                  NVARCHAR (150)     NULL,
    [client_interface_name]                   NVARCHAR (32)      NULL,
    [login_time]                              DATETIME           NOT NULL,
    [start_time]                              DATETIME           NULL,
    [request_time]                            DATETIME           NULL,
    [request_cpu_time]                        INT                NULL,
    [request_logical_reads]                   BIGINT             NULL,
    [request_writes]                          BIGINT             NULL,
    [request_physical_reads]                  BIGINT             NULL,
    [session_cpu]                             INT                NOT NULL,
    [session_logical_reads]                   BIGINT             NOT NULL,
    [session_physical_reads]                  BIGINT             NOT NULL,
    [session_writes]                          BIGINT             NOT NULL,
    [tempdb_allocations_mb]                   DECIMAL (38, 2)    NULL,
    [memory_usage]                            INT                NOT NULL,
    [estimated_completion_time]               BIGINT             NULL,
    [percent_complete]                        REAL               NULL,
    [deadlock_priority]                       INT                NULL,
    [transaction_isolation_level]             VARCHAR (33)       NOT NULL,
    [degree_of_parallelism]                   SMALLINT           NULL,
    [last_dop]                                BIGINT             NULL,
    [min_dop]                                 BIGINT             NULL,
    [max_dop]                                 BIGINT             NULL,
    [last_grant_kb]                           BIGINT             NULL,
    [min_grant_kb]                            BIGINT             NULL,
    [max_grant_kb]                            BIGINT             NULL,
    [last_used_grant_kb]                      BIGINT             NULL,
    [min_used_grant_kb]                       BIGINT             NULL,
    [max_used_grant_kb]                       BIGINT             NULL,
    [last_ideal_grant_kb]                     BIGINT             NULL,
    [min_ideal_grant_kb]                      BIGINT             NULL,
    [max_ideal_grant_kb]                      BIGINT             NULL,
    [last_reserved_threads]                   BIGINT             NULL,
    [min_reserved_threads]                    BIGINT             NULL,
    [max_reserved_threads]                    BIGINT             NULL,
    [last_used_threads]                       BIGINT             NULL,
    [min_used_threads]                        BIGINT             NULL,
    [max_used_threads]                        BIGINT             NULL,
    [grant_time]                              VARCHAR (20)       NULL,
    [requested_memory_kb]                     BIGINT             NULL,
    [grant_memory_kb]                         BIGINT             NULL,
    [is_request_granted]                      VARCHAR (39)       NOT NULL,
    [required_memory_kb]                      BIGINT             NULL,
    [query_memory_grant_used_memory_kb]       BIGINT             NULL,
    [ideal_memory_kb]                         BIGINT             NULL,
    [is_small]                                BIT                NULL,
    [timeout_sec]                             INT                NULL,
    [resource_semaphore_id]                   SMALLINT           NULL,
    [wait_order]                              VARCHAR (20)       NULL,
    [wait_time_ms]                            VARCHAR (20)       NULL,
    [next_candidate_for_memory_grant]         VARCHAR (3)        NOT NULL,
    [target_memory_kb]                        BIGINT             NULL,
    [max_target_memory_kb]                    VARCHAR (30)       NULL,
    [total_memory_kb]                         BIGINT             NULL,
    [available_memory_kb]                     BIGINT             NULL,
    [granted_memory_kb]                       BIGINT             NULL,
    [query_resource_semaphore_used_memory_kb] BIGINT             NULL,
    [grantee_count]                           INT                NULL,
    [waiter_count]                            INT                NULL,
    [timeout_error_count]                     BIGINT             NULL,
    [forced_grant_count]                      VARCHAR (30)       NULL,
    [workload_group_name]                     [sysname]          NULL,
    [resource_pool_name]                      [sysname]          NULL,
    [context_info]                            VARCHAR (128)      NULL,
    [query_hash]                              BINARY (8)         NULL,
    [query_plan_hash]                         BINARY (8)         NULL,
    [sql_handle]                              VARBINARY (64)     NULL,
    [plan_handle]                             VARBINARY (64)     NULL,
    [statement_start_offset]                  INT                NULL,
    [statement_end_offset]                    INT                NULL,
    [JoinKey]                                 AS                 ([ServerName]+CONVERT([nvarchar](50),[CheckDate])),
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

