CREATE TABLE [dbo].[WhoIsActive] (
    [collection_time]          DATETIME        NOT NULL,
    [host_cpu_percent]         TINYINT         DEFAULT ((0)) NOT NULL,
    [cpu_rank]                 SMALLINT        DEFAULT ((0)) NOT NULL,
    [CPU_delta_percent]        TINYINT         NOT NULL,
    [pool]                     VARCHAR (30)    NULL,
    [dd hh:mm:ss.mss]          VARCHAR (8000)  NULL,
    [session_id]               SMALLINT        NOT NULL,
    [program_name]             NVARCHAR (128)  NULL,
    [login_name]               NVARCHAR (128)  NOT NULL,
    [database_name]            NVARCHAR (128)  NULL,
    [CPU]                      VARCHAR (30)    NULL,
    [CPU_delta]                VARCHAR (30)    NULL,
    [used_memory]              VARCHAR (30)    NULL,
    [used_memory_delta]        VARCHAR (30)    NULL,
    [open_tran_count]          VARCHAR (30)    NULL,
    [status]                   VARCHAR (30)    NOT NULL,
    [wait_info]                NVARCHAR (4000) NULL,
    [sql_command]              XML             NULL,
    [blocked_session_count]    VARCHAR (30)    NULL,
    [blocking_session_id]      SMALLINT        NULL,
    [sql_text]                 XML             NULL,
    [dd hh:mm:ss.mss (avg)]    VARCHAR (15)    NULL,
    [physical_io]              VARCHAR (30)    NULL,
    [reads]                    VARCHAR (30)    NULL,
    [physical_reads]           VARCHAR (30)    NULL,
    [writes]                   VARCHAR (30)    NULL,
    [tempdb_allocations]       VARCHAR (30)    NULL,
    [tempdb_current]           VARCHAR (30)    NULL,
    [context_switches]         VARCHAR (30)    NULL,
    [physical_io_delta]        VARCHAR (30)    NULL,
    [reads_delta]              VARCHAR (30)    NULL,
    [physical_reads_delta]     VARCHAR (30)    NULL,
    [writes_delta]             VARCHAR (30)    NULL,
    [tempdb_allocations_delta] VARCHAR (30)    NULL,
    [tempdb_current_delta]     VARCHAR (30)    NULL,
    [context_switches_delta]   VARCHAR (30)    NULL,
    [tasks]                    VARCHAR (30)    NULL,
    [query_plan]               XML             NULL,
    [percent_complete]         VARCHAR (30)    NULL,
    [host_name]                NVARCHAR (128)  NULL,
    [additional_info]          XML             NULL,
    [start_time]               DATETIME        NOT NULL,
    [login_time]               DATETIME        NULL,
    [request_id]               INT             NULL,
    [CPU_delta_all]            BIGINT          NOT NULL,
    [duration_minutes]         AS              ((datediff_big(millisecond,[start_time],[collection_time])/(1000))/(60)),
    CONSTRAINT [pk_WhoIsActive] PRIMARY KEY CLUSTERED ([collection_time] ASC, [cpu_rank] ASC) ON [ps_dba_datetime] ([collection_time])
) ON [ps_dba_datetime] ([collection_time]);

