{
 "title": "t___Database File IO Stats",
 "description": "Data of sys.dm_os_wait_stats",
 "tags": [
  "mssql",
  "sqlserver"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "mssql" },
   {
    "name": "server",
    "label": "Sql Instance",
    "query": "declare @sql nvarchar(max);\n\nset quoted_identifier off;\nset @sql = \"select distinct srvname = sql_instance from dbo.instance_details with (nolock)\nwhere is_available = 1\n\";\nset quoted_identifier off;\n\nexec dbo.sp_executesql @sql;"
   },
   { "name": "inventory_db", "label": "Inventory Database", "query": "SELECT DB_NAME()" },
   {
    "name": "is_local",
    "label": "Is Local SQL Instance",
    "query": "declare @sql_instance varchar(255); \nset @sql_instance = '$server';\nselect is_local = case when ( (CONVERT(varchar,SERVERPROPERTY('MachineName')) = @sql_instance ) \n\t\t\tor (CONVERT(varchar,SERVERPROPERTY('ServerName')) = @sql_instance )\n\t\t\t)  then 1 else 0 end"
   },
   {
    "name": "dba_db",
    "label": "DBA Database",
    "query": "declare @sql nvarchar(max);\ndeclare @sql_instance varchar(255);\nset @sql_instance = '$server';\n\nset quoted_identifier off;\nset @sql = \"select [database] from dbo.instance_details id\nwhere id.sql_instance = @sql_instance\n\";\nset quoted_identifier off;\n\nexec dbo.sp_executesql @sql, N'@sql_instance varchar(255)', @sql_instance;"
   },
   {
    "name": "ip",
    "label": "IP Address",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n\nset @sql_instance = '$server';\nset @params = N'@sql_instance varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select CONVERT(varchar,  CONNECTIONPROPERTY('local_net_address') ) as [ip];\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql --, @params, @sql_instance;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql --, @params, @sql_instance;"
   },
   {
    "name": "fqdn",
    "label": "FQDN",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n\nset @sql_instance = '$server';\nset @params = N'@sql_instance varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"declare @fqdn nvarchar(100);\nexec usp_extended_results @fqdn = @fqdn output;\n\nselect case when default_domain() = 'WORKGROUP' then 'WORKGROUP' ELSE @fqdn END\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql --, @params, @sql_instance;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql --, @params, @sql_instance;"
   },
   {
    "name": "collection_time_utc",
    "label": "Collection Time UTC",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n--declare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n--set @delta_minutes = $cpu_delta_minutes;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2';\n\nset quoted_identifier off;\nset @sql = \"\nset nocount on;\nselect top 1 collection_time_utc\nfrom [dbo].[file_io_stats]\norder by collection_time_utc desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc;"
   },
   {
    "name": "sql_schedulers",
    "label": "SQL Schedulers",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select count(*) as counts from sys.dm_os_schedulers dos where status = 'VISIBLE ONLINE' and is_online = 1;\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   {
    "name": "sqlserver_start_time_utc",
    "label": "SqlInstance Start Time UTC",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\nset @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), sqlserver_start_time) from sys.dm_os_sys_info as osi;\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   {
    "name": "disk_drive",
    "label": "Disk Drive",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select ds.disk_volume as disk_drive\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\tunion all\n\tselect '__All__' as disk_drive\n\torder by disk_drive\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select name from sys.databases d where d.state_desc = 'ONLINE' union all select '__All__' as name order by name;\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   }
  ]
 },
 "panels": [
  {
   "title": "File IO Stats - Since Startup__till____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - \"__${sql_schedulers} CPUs__\"  - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "File IO Stats ____Since Startup ___ till ___ ${collection_time_utc:date:YYYY-MM-DD HH.mm}___",
     "type": "table",
     "description": "exec sp_BlitzFirst @seconds = 60, @ExpertMode = 1",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n--declare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\ndeclare @disk_drive varchar(255) = '$disk_drive';\ndeclare @database varchar(255) = '$database';\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @disk_drive = case when ltrim(rtrim(@disk_drive)) = '__All__' then null else @disk_drive end;\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n--set @delta_minutes = $cpu_delta_minutes;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @disk_drive varchar(255), @database varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - File IO Stats Since Startup */\nset nocount on;\ndeclare @start_time datetime;\ndeclare @schedulers smallint;\ndeclare @cpu_time_min decimal(18,1);\ndeclare @IOStatsTop tinyint = 10;\ndeclare @IOPercentTop int = 99;\n\nselect @start_time = sqlserver_start_time from sys.dm_os_sys_info;\nselect @schedulers = count(*) from sys.dm_os_schedulers where status = 'VISIBLE ONLINE' and is_online = 1;\n-- @cpu_time_min = sum(total_cpu_usage_ms/1000.0)/60.0\n\n;WITH [t_DiskDrives] AS (\n\tselect ds.disk_volume\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\t\"+(case when @disk_drive is null then '-- ' else '' end)+\"and ds.disk_volume = @disk_drive\n)\n,[t_FileIO] AS\n\t(\tSELECT\n\t    [running_query] = 'File IO Stats', [collection_time_utc], [sample_ms], [database_name], \n\t    [file_name_DISPLAY] = [file_logical_name]+' '+QUOTENAME(case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end),\n\t    [file_logical_name], [file_location], dv.disk_volume, [size_on_disk_bytes],\n\t\t\t[file_type] = case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end,\n\n\t\t\t[total_reads_writes] = [num_of_reads] + [num_of_writes], \n\t\t\t[num_of_bytes_read], [num_of_bytes_written], \n\t\t\t[total_reads_writes_bytes] = [num_of_bytes_read]+[num_of_bytes_written],\n\t\t\t\n\t\t\t[reads_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[writes_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)) + ' / ' + convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)),\n\n\t\t\t--[num_of_reads], [io_stall_read_ms], [num_of_writes],  [io_stall_write_ms],\n\t\t\t--[io_stall], [io_pending_ms_ticks_total],\n\t\t\t\n\t\t\t[read_latency_ms] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else (([io_stall_read_ms] * 1.0)/[num_of_reads]) end),\n\t\t\t[write_latency_ms] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else (([io_stall_write_ms] * 1.0)/[num_of_writes]) end),\n\t\t\t[latency_ms] = convert(numeric(20,2), case when [num_of_reads] + [num_of_writes] = 0 then 0 else (([io_stall] * 1.0) / ([num_of_reads] + [num_of_writes])) end),\n\n\t\t\t[avg_bytes_per_read] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else ( ([num_of_bytes_read] * 1.0) / [num_of_reads] ) end),\n\t\t\t[avg_bytes_per_write] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else ( ([num_of_bytes_written] * 1.0) / [num_of_writes] ) end),\n\t\t\t[avg_bytes_per_transfer] = convert(numeric(20,2), case when [num_of_reads] = 0 and [num_of_writes] = 0 then 0 else ( (([num_of_bytes_read]+[num_of_bytes_written]) * 1.0) / ([num_of_reads]+[num_of_writes]) ) end)\n\t\t\t\n\t\tFROM dbo.file_io_stats fis\n\t\tCROSS APPLY (\n\t\t\t\tselect top 1 dd.disk_volume\n\t\t\t\tfrom [t_DiskDrives] dd\n\t\t\t\twhere fis.file_location like (dd.disk_volume+'%')\n\t\t\t\torder by len(dd.disk_volume) desc\n\t\t\t) dv\n\t\tWHERE fis.collection_time_utc = (SELECT MAX(i.collection_time_utc) FROM dbo.file_io_stats i)\n\t\t\"+(case when @database is null then '-- ' else '' end)+\"AND fis.[database_name] = @database\n    )\nselect *\nfrom [t_FileIO] fio\norder by ([num_of_bytes_read]+[num_of_bytes_written]) desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;"
      }
     ]
    }
   ]
  },
  {
   "title": "File IO Stats - Selective - \"__${sql_schedulers} CPUs__\" @ ${collection_time_utc:date:YYYY-MM-DD HH.mm}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "File IO Stats ____Since Startup ___ till ___ ${__from:date:YYYY-MM-DD HH.mm}___",
     "type": "table",
     "description": "exec sp_BlitzFirst @seconds = 60, @ExpertMode = 1",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\ndeclare @disk_drive varchar(255) = '$disk_drive';\ndeclare @database varchar(255) = '$database';\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\n--set @start_time_utc = $__timeFrom();\nset @start_time_utc = dateadd(second,$sqlserver_start_time_utc/1000,'1970-01-01 00:00:00');\n--set @end_time_utc = $__timeTo();\nset @end_time_utc = $__timeFrom();\n--select @start_time_utc as start_time, @end_time_utc as end_time;\n--set @delta_minutes = $cpu_delta_minutes;\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @disk_drive = case when ltrim(rtrim(@disk_drive)) = '__All__' then null else @disk_drive end;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @disk_drive varchar(255), @database varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"\nset nocount on;\ndeclare @schedulers smallint;\ndeclare @StatstatsTop tinyint = 10;\ndeclare @StatsPercentTop int = 99;\ndeclare @collect_time_utc_snap1 datetime2;\ndeclare @collect_time_utc_snap2 datetime2;\n\n--select @start_time_utc = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), sqlserver_start_time) from sys.dm_os_sys_info;\nselect @schedulers = count(*) from sys.dm_os_schedulers where status = 'VISIBLE ONLINE' and is_online = 1;\n\nselect top 1 @collect_time_utc_snap2 = collection_time_utc\nfrom dbo.file_io_stats s2\nwhere s2.collection_time_utc <= @end_time_utc\norder by collection_time_utc desc;\n\nselect top 1 @collect_time_utc_snap1 = collection_time_utc\nfrom dbo.file_io_stats s1\nwhere collection_time_utc >= @start_time_utc\norder by collection_time_utc asc;\n\n--select @collect_time_utc_snap1, @collect_time_utc_snap2;\n\n;WITH [DiffStats] AS\n(\tSELECT\t-- Stats that weren't in the first snapshot\n\t\t\t--[ts2].[collection_time_utc],\n\t\t\t[ts2].[database_name],\n\t\t\t[ts2].[database_id],\n\t\t\t[ts2].[file_logical_name],\n\t\t\t[ts2].[file_id],\n\t\t\t[ts2].[file_location],\n\t\t\t[ts2].[sample_ms],\n\t\t\t[ts2].[num_of_reads],\n\t\t\t[ts2].[num_of_bytes_read],\n\t\t\t[ts2].[io_stall_read_ms],\n\t\t\t[ts2].[io_stall_queued_read_ms],\n\t\t\t[ts2].[num_of_writes],\n\t\t\t[ts2].[num_of_bytes_written],\n\t\t\t[ts2].[io_stall_write_ms],\n\t\t\t[ts2].[io_stall_queued_write_ms],\n\t\t\t[ts2].[io_stall],\n\t\t\t[ts2].[size_on_disk_bytes],\n\t\t\t[ts2].[io_pending_count]\n\tFROM dbo.file_io_stats AS [ts2]\n\tLEFT OUTER JOIN dbo.file_io_stats AS [ts1]\n\t\tON [ts2].[database_name] = [ts1].[database_name]\n\t\tAND [ts2].[file_logical_name] = [ts1].[file_logical_name]\n\t\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\tAND [ts1].collection_time_utc = @collect_time_utc_snap1\n\tWHERE [ts1].[file_logical_name] IS NULL\n\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts1.[database_name] = @database\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts2.[database_name] = @database\n\t--\n\tUNION\n\t--\n\tSELECT\t-- Diff of Stats in both snapshots\n\t\t\t--[collection_time_utc] = [ts2].[collection_time_utc] - [ts1].[collection_time_utc],\n\t\t\t[database_name] = [ts2].[database_name],\n\t\t\t[database_id] = [ts2].[database_id],\n\t\t\t[file_logical_name] = [ts2].[file_logical_name],\n\t\t\t[file_id] = [ts2].[file_id],\n\t\t\t[file_location] = [ts2].[file_location],\n\t\t\t[sample_ms] = [ts2].[sample_ms] - [ts1].[sample_ms],\n\t\t\t[num_of_reads] = [ts2].[num_of_reads] - [ts1].[num_of_reads],\n\t\t\t[num_of_bytes_read] = [ts2].[num_of_bytes_read] - [ts1].[num_of_bytes_read],\n\t\t\t[io_stall_read_ms] = [ts2].[io_stall_read_ms] - [ts1].[io_stall_read_ms],\n\t\t\t[io_stall_queued_read_ms] = [ts2].[io_stall_queued_read_ms] - [ts1].[io_stall_queued_read_ms],\n\t\t\t[num_of_writes] = [ts2].[num_of_writes] - [ts1].[num_of_writes],\n\t\t\t[num_of_bytes_written] = [ts2].[num_of_bytes_written] - [ts1].[num_of_bytes_written],\n\t\t\t[io_stall_write_ms] = [ts2].[io_stall_write_ms] - [ts1].[io_stall_write_ms],\n\t\t\t[io_stall_queued_write_ms] = [ts2].[io_stall_queued_write_ms] - [ts1].[io_stall_queued_write_ms],\n\t\t\t[io_stall] = [ts2].[io_stall] - [ts1].[io_stall],\n\t\t\t[size_on_disk_bytes] = [ts2].[size_on_disk_bytes],\n\t\t\t[io_pending_count] = [ts2].[io_pending_count] - [ts1].[io_pending_count]\n\tFROM dbo.file_io_stats AS [ts2]\n\tLEFT OUTER JOIN dbo.file_io_stats AS [ts1]\n\t\tON [ts2].[database_name] = [ts1].[database_name]\n\t\tAND [ts2].[file_logical_name] = [ts1].[file_logical_name]\n\t\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\tAND [ts1].collection_time_utc = @collect_time_utc_snap1\n\tWHERE [ts1].[file_logical_name] IS NOT NULL\n\tAND ( ([ts2].[num_of_reads]+[ts2].[num_of_writes]) - ([ts1].[num_of_reads]+[ts1].[num_of_writes]) ) > 0\n\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts1.[database_name] = @database\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts2.[database_name] = @database\n)\n,[t_DiskDrives] AS \n(\tselect ds.disk_volume\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\t\"+(case when @disk_drive is null then '-- ' else '' end)+\"and ds.disk_volume = @disk_drive\n)\n,[t_FileIO] AS\n(\tSELECT\t[running_query] = 'File IO Stats', [sample_ms], [database_name], \n\t\t\t[file_name_DISPLAY] = [file_logical_name]+' '+QUOTENAME(case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end),\n\t\t\t[file_logical_name], [file_location], dv.disk_volume, [size_on_disk_bytes],\n\t\t\t[file_type] = case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end,\n\n\t\t\t[total_reads_writes] = [num_of_reads] + [num_of_writes], \n\t\t\t[num_of_bytes_read], [num_of_bytes_written], \n\t\t\t[total_reads_writes_bytes] = [num_of_bytes_read]+[num_of_bytes_written],\n\t\t\t\n\t\t\t[reads_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[writes_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)) + ' / ' + convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)),\n\n\t\t\t--[num_of_reads], [io_stall_read_ms], [num_of_writes],  [io_stall_write_ms],\n\t\t\t--[io_stall], [io_pending_ms_ticks_total],\n\t\t\t\n\t\t\t[read_latency_ms] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else (([io_stall_read_ms] * 1.0)/[num_of_reads]) end),\n\t\t\t[write_latency_ms] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else (([io_stall_write_ms] * 1.0)/[num_of_writes]) end),\n\t\t\t[latency_ms] = convert(numeric(20,2), case when [num_of_reads] + [num_of_writes] = 0 then 0 else (([io_stall] * 1.0) / ([num_of_reads] + [num_of_writes])) end),\n\n\t\t\t[avg_bytes_per_read] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else ( ([num_of_bytes_read] * 1.0) / [num_of_reads] ) end),\n\t\t\t[avg_bytes_per_write] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else ( ([num_of_bytes_written] * 1.0) / [num_of_writes] ) end),\n\t\t\t[avg_bytes_per_transfer] = convert(numeric(20,2), case when [num_of_reads] = 0 and [num_of_writes] = 0 then 0 else ( (([num_of_bytes_read]+[num_of_bytes_written]) * 1.0) / ([num_of_reads]+[num_of_writes]) ) end)\n\tFROM [DiffStats] fis\n\tCROSS APPLY (\n\t\t\tselect top 1 dd.disk_volume\n\t\t\tfrom [t_DiskDrives] dd\n\t\t\twhere fis.file_location like (dd.disk_volume+'%')\n\t\t\torder by len(dd.disk_volume) desc\n\t\t) dv\n)\nselect *\nfrom [t_FileIO] fio\norder by ([num_of_bytes_read]+[num_of_bytes_written]) desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;"
      }
     ]
    },
    {
     "title": "File IO Stats ____In Selected Time Duration____Since____${__from:date:YYYY-MM-DD HH.mm}___till___${__to:date:YYYY-MM-DD HH.mm}____",
     "type": "table",
     "description": "exec sp_BlitzFirst @seconds = 60, @ExpertMode = 1",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n--declare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\ndeclare @disk_drive varchar(255) = '$disk_drive';\ndeclare @database varchar(255) = '$database';\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n--set @delta_minutes = $cpu_delta_minutes;\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @disk_drive = case when ltrim(rtrim(@disk_drive)) = '__All__' then null else @disk_drive end;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @disk_drive varchar(255), @database varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"\nset nocount on;\ndeclare @schedulers smallint;\ndeclare @StatstatsTop tinyint = 10;\ndeclare @StatsPercentTop int = 99;\ndeclare @collect_time_utc_snap1 datetime2;\ndeclare @collect_time_utc_snap2 datetime2;\n\n--select @start_time_utc = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), sqlserver_start_time) from sys.dm_os_sys_info;\nselect @schedulers = count(*) from sys.dm_os_schedulers where status = 'VISIBLE ONLINE' and is_online = 1;\n\nselect top 1 @collect_time_utc_snap2 = collection_time_utc\nfrom dbo.file_io_stats s2\nwhere s2.collection_time_utc <= @end_time_utc\norder by collection_time_utc desc;\n\nselect top 1 @collect_time_utc_snap1 = collection_time_utc\nfrom dbo.file_io_stats s1\nwhere collection_time_utc >= @start_time_utc\norder by collection_time_utc asc;\n\n--select @collect_time_utc_snap1, @collect_time_utc_snap2;\n\n;WITH [DiffStats] AS\n(\tSELECT\t-- Stats that weren't in the first snapshot\n\t\t\t--[ts2].[collection_time_utc],\n\t\t\t[ts2].[database_name],\n\t\t\t[ts2].[database_id],\n\t\t\t[ts2].[file_logical_name],\n\t\t\t[ts2].[file_id],\n\t\t\t[ts2].[file_location],\n\t\t\t[ts2].[sample_ms],\n\t\t\t[ts2].[num_of_reads],\n\t\t\t[ts2].[num_of_bytes_read],\n\t\t\t[ts2].[io_stall_read_ms],\n\t\t\t[ts2].[io_stall_queued_read_ms],\n\t\t\t[ts2].[num_of_writes],\n\t\t\t[ts2].[num_of_bytes_written],\n\t\t\t[ts2].[io_stall_write_ms],\n\t\t\t[ts2].[io_stall_queued_write_ms],\n\t\t\t[ts2].[io_stall],\n\t\t\t[ts2].[size_on_disk_bytes],\n\t\t\t[ts2].[io_pending_count]\n\tFROM dbo.file_io_stats AS [ts2]\n\tLEFT OUTER JOIN dbo.file_io_stats AS [ts1]\n\t\tON [ts2].[database_name] = [ts1].[database_name]\n\t\tAND [ts2].[file_logical_name] = [ts1].[file_logical_name]\n\t\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\tAND [ts1].collection_time_utc = @collect_time_utc_snap1\n\tWHERE [ts1].[file_logical_name] IS NULL\n\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts1.[database_name] = @database\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts2.[database_name] = @database\n\t--\n\tUNION\n\t--\n\tSELECT\t-- Diff of Stats in both snapshots\n\t\t\t--[collection_time_utc] = [ts2].[collection_time_utc] - [ts1].[collection_time_utc],\n\t\t\t[database_name] = [ts2].[database_name],\n\t\t\t[database_id] = [ts2].[database_id],\n\t\t\t[file_logical_name] = [ts2].[file_logical_name],\n\t\t\t[file_id] = [ts2].[file_id],\n\t\t\t[file_location] = [ts2].[file_location],\n\t\t\t[sample_ms] = [ts2].[sample_ms] - [ts1].[sample_ms],\n\t\t\t[num_of_reads] = [ts2].[num_of_reads] - [ts1].[num_of_reads],\n\t\t\t[num_of_bytes_read] = [ts2].[num_of_bytes_read] - [ts1].[num_of_bytes_read],\n\t\t\t[io_stall_read_ms] = [ts2].[io_stall_read_ms] - [ts1].[io_stall_read_ms],\n\t\t\t[io_stall_queued_read_ms] = [ts2].[io_stall_queued_read_ms] - [ts1].[io_stall_queued_read_ms],\n\t\t\t[num_of_writes] = [ts2].[num_of_writes] - [ts1].[num_of_writes],\n\t\t\t[num_of_bytes_written] = [ts2].[num_of_bytes_written] - [ts1].[num_of_bytes_written],\n\t\t\t[io_stall_write_ms] = [ts2].[io_stall_write_ms] - [ts1].[io_stall_write_ms],\n\t\t\t[io_stall_queued_write_ms] = [ts2].[io_stall_queued_write_ms] - [ts1].[io_stall_queued_write_ms],\n\t\t\t[io_stall] = [ts2].[io_stall] - [ts1].[io_stall],\n\t\t\t[size_on_disk_bytes] = [ts2].[size_on_disk_bytes],\n\t\t\t[io_pending_count] = [ts2].[io_pending_count] - [ts1].[io_pending_count]\n\tFROM dbo.file_io_stats AS [ts2]\n\tLEFT OUTER JOIN dbo.file_io_stats AS [ts1]\n\t\tON [ts2].[database_name] = [ts1].[database_name]\n\t\tAND [ts2].[file_logical_name] = [ts1].[file_logical_name]\n\t\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\tAND [ts1].collection_time_utc = @collect_time_utc_snap1\n\tWHERE [ts1].[file_logical_name] IS NOT NULL\n\tAND ( ([ts2].[num_of_reads]+[ts2].[num_of_writes]) - ([ts1].[num_of_reads]+[ts1].[num_of_writes]) ) > 0\n\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts1.[database_name] = @database\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts2.[database_name] = @database\n)\n,[t_DiskDrives] AS \n(\tselect ds.disk_volume\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\t\"+(case when @disk_drive is null then '-- ' else '' end)+\"and ds.disk_volume = @disk_drive\n)\n,[t_FileIO] AS\n(\tSELECT\t[running_query] = 'File IO Stats', [sample_ms], [database_name], \n\t\t\t[file_name_DISPLAY] = [file_logical_name]+' '+QUOTENAME(case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end),\n\t\t\t[file_logical_name], [file_location], dv.disk_volume, [size_on_disk_bytes],\n\t\t\t[file_type] = case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end,\n\n\t\t\t[total_reads_writes] = [num_of_reads] + [num_of_writes], \n\t\t\t[num_of_bytes_read], [num_of_bytes_written], \n\t\t\t[total_reads_writes_bytes] = [num_of_bytes_read]+[num_of_bytes_written],\n\t\t\t\n\t\t\t[reads_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[writes_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)) + ' / ' + convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)),\n\n\t\t\t--[num_of_reads], [io_stall_read_ms], [num_of_writes],  [io_stall_write_ms],\n\t\t\t--[io_stall], [io_pending_ms_ticks_total],\n\t\t\t\n\t\t\t[read_latency_ms] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else (([io_stall_read_ms] * 1.0)/[num_of_reads]) end),\n\t\t\t[write_latency_ms] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else (([io_stall_write_ms] * 1.0)/[num_of_writes]) end),\n\t\t\t[latency_ms] = convert(numeric(20,2), case when [num_of_reads] + [num_of_writes] = 0 then 0 else (([io_stall] * 1.0) / ([num_of_reads] + [num_of_writes])) end),\n\n\t\t\t[avg_bytes_per_read] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else ( ([num_of_bytes_read] * 1.0) / [num_of_reads] ) end),\n\t\t\t[avg_bytes_per_write] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else ( ([num_of_bytes_written] * 1.0) / [num_of_writes] ) end),\n\t\t\t[avg_bytes_per_transfer] = convert(numeric(20,2), case when [num_of_reads] = 0 and [num_of_writes] = 0 then 0 else ( (([num_of_bytes_read]+[num_of_bytes_written]) * 1.0) / ([num_of_reads]+[num_of_writes]) ) end)\n\tFROM [DiffStats] fis\n\tCROSS APPLY (\n\t\t\tselect top 1 dd.disk_volume\n\t\t\tfrom [t_DiskDrives] dd\n\t\t\twhere fis.file_location like (dd.disk_volume+'%')\n\t\t\torder by len(dd.disk_volume) desc\n\t\t) dv\n)\nselect *\nfrom [t_FileIO] fio\norder by ([num_of_bytes_read]+[num_of_bytes_written]) desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;"
      }
     ]
    }
   ]
  },
  {
   "title": "File IO Stats - Reads/Writes (Data) - Histogram -  [$fqdn] - [$ip] - @ ${collection_time_utc:date:YYYY-MM-DD HH.mm}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "[${server}] - Db File IO Stats - Read/Writes Data",
     "type": "timeseries",
     "description": "exec sp_BlitzFirst @seconds = 60, @ExpertMode = 1",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\ndeclare @disk_drive varchar(255) = '$disk_drive';\ndeclare @database varchar(255) = '$database';\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @disk_drive = case when ltrim(rtrim(@disk_drive)) = '__All__' then null else @disk_drive end;\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @start_time_utc = $__timeFrom();\n--set @start_time_utc = dateadd(second,$sqlserver_start_time_utc/1000,'1970-01-01 00:00:00');\nset @end_time_utc = $__timeTo();\n--set @end_time_utc = $__timeFrom();\n--set @delta_minutes = $cpu_delta_minutes;\nset @params = N'@perfmon_host_name varchar(255), @start_time_utc datetime2, @end_time_utc datetime2, @disk_drive varchar(255), @database varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"\nset nocount on;\ndeclare @FileIOStatsTop tinyint = 10;\ndeclare @StatsPercentTop int = 99;\n\n;WITH [Stats] AS\n(\n\tSELECT\t[collection_time_utc],\n\t\t\t[database_name],\n\t\t\t--[database_id],\n\t\t\t[file_logical_name],\n\t\t\t--[file_id],\n\t\t\t[file_location],\n\t\t\t[sample_ms_delta],\n\t\t\t--[num_of_reads],\n\t\t\t[read_write_bytes_delta],\n\t\t\t[read_bytes_delta],\n\t\t\t--[io_stall_read_ms],\n\t\t\t--[io_stall_queued_read_ms],\n\t\t\t--[num_of_writes],\n\t\t\t[writes_bytes_delta],\n\t\t\t--[io_stall_write_ms],\n\t\t\t--[io_stall_queued_write_ms],\n\t\t\t--[io_stall],\n\t\t\t[io_stall_delta],\n\t\t\t--[size_on_disk_bytes],\n\t\t\t--[io_pending_count],\n\t\t\t--[io_pending_ms_ticks_total],\n\t\t\t--[io_pending_ms_ticks_avg],\n\t\t\t--[io_pending_ms_ticks_max],\n\t\t\t--[io_pending_ms_ticks_min]\n\t\t\t[StatsRank] = ROW_NUMBER() OVER(PARTITION BY [collection_time_utc] ORDER BY read_write_bytes_delta DESC),\n\t\t\t[Percentage] = ((100.0 * [read_write_bytes_delta]) / (SUM ([read_write_bytes_delta]) OVER (PARTITION BY [collection_time_utc]))),\n\t\t\t[PercentageTotal] = ( (100.0 * ( SUM([read_write_bytes_delta]) \n\t\t\t\t\t\t\t\t\t\t\t OVER(PARTITION BY [collection_time_utc] \n\t\t\t\t\t\t\t\t\t\t\t ORDER BY [read_write_bytes_delta] DESC, [io_stall_delta] desc) )\n\t\t\t\t\t\t\t\t  ) / (SUM ([read_write_bytes_delta]) OVER (PARTITION BY [collection_time_utc])) )\n\tFROM dbo.[vw_file_io_stats_deltas] AS [Stats]\n\tWHERE collection_time_utc between @start_time_utc and @end_time_utc\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND [Stats].[database_name] = @database\n\t\"+(case when @disk_drive is null then '-- ' else '' end)+\"and [Stats].disk_volume = @disk_drive\n)\nSELECT\ttime = [collection_time_utc]\n\t\t--,[database_name]\n\t\t,[metric] =  [database_name]+ ' (__ '+[file_logical_name]+' __)'\n\t\t--,[file_logical_name]\n\t\t--,[file_location]\n\t\t--,[sample_ms_delta]\n\t\t--,[read_write_bytes_delta]\n\t\t--,[read_bytes_delta]\n\t\t--,[writes_bytes_delta]\n\t\t--,[StatsRank]\n\t\t--,[Percentage]\n\t\t--,[PercentageTotal]\n\t\t,[value] = [read_write_bytes_delta]\nFROM [Stats] as cur\nWHERE [StatsRank] <= @FileIOStatsTop\nAND [PercentageTotal] <= @StatsPercentTop\nORDER BY [time] ASC, [read_write_bytes_delta] DESC, [io_stall_delta] DESC\nOPTION(RECOMPILE);\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @perfmon_host_name, @start_time_utc, @end_time_utc, @disk_drive, @database;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @perfmon_host_name, @start_time_utc, @end_time_utc, @disk_drive, @database;"
      }
     ]
    }
   ]
  },
  {
   "title": "File IO Stats - Read/Writes (#) - Histogram -  [$fqdn] - [$ip] - @ ${collection_time_utc:date:YYYY-MM-DD HH.mm}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "[${server}] - Db File IO Stats - # Read/Writes",
     "type": "timeseries",
     "description": "exec sp_BlitzFirst @seconds = 60, @ExpertMode = 1",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\ndeclare @disk_drive varchar(255) = '$disk_drive';\ndeclare @database varchar(255) = '$database';\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @disk_drive = case when ltrim(rtrim(@disk_drive)) = '__All__' then null else @disk_drive end;\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @start_time_utc = $__timeFrom();\n--set @start_time_utc = dateadd(second,$sqlserver_start_time_utc/1000,'1970-01-01 00:00:00');\nset @end_time_utc = $__timeTo();\n--set @end_time_utc = $__timeFrom();\n--set @delta_minutes = $cpu_delta_minutes;\nset @params = N'@perfmon_host_name varchar(255), @start_time_utc datetime2, @end_time_utc datetime2, @disk_drive varchar(255), @database varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"\nset nocount on;\ndeclare @FileIOStatsTop tinyint = 10;\ndeclare @StatsPercentTop int = 99;\n\n;WITH [Stats] AS\n(\n\tSELECT\t[collection_time_utc],\n\t\t\t[database_name],\n\t\t\t--[database_id],\n\t\t\t[file_logical_name],\n\t\t\t--[file_id],\n\t\t\t[file_location],\n\t\t\t[sample_ms_delta],\n\t\t\t--[num_of_reads],\n\t\t\t[read_write_bytes_delta],\n\t\t\t[read_writes_delta],\n\t\t\t[read_bytes_delta],\n\t\t\t--[io_stall_read_ms],\n\t\t\t--[io_stall_queued_read_ms],\n\t\t\t--[num_of_writes],\n\t\t\t[writes_bytes_delta],\n\t\t\t--[io_stall_write_ms],\n\t\t\t--[io_stall_queued_write_ms],\n\t\t\t--[io_stall],\n\t\t\t[io_stall_delta],\n\t\t\t--[size_on_disk_bytes],\n\t\t\t--[io_pending_count],\n\t\t\t--[io_pending_ms_ticks_total],\n\t\t\t--[io_pending_ms_ticks_avg],\n\t\t\t--[io_pending_ms_ticks_max],\n\t\t\t--[io_pending_ms_ticks_min]\n\t\t\t[StatsRank] = ROW_NUMBER() OVER(PARTITION BY [collection_time_utc] ORDER BY read_writes_delta DESC),\n\t\t\t[Percentage] = ((100.0 * [read_writes_delta]) / (SUM ([read_writes_delta]) OVER (PARTITION BY [collection_time_utc]))),\n\t\t\t[PercentageTotal] = ( (100.0 * ( SUM([read_writes_delta]) \n\t\t\t\t\t\t\t\t\t\t\t OVER(PARTITION BY [collection_time_utc] \n\t\t\t\t\t\t\t\t\t\t\t ORDER BY [read_writes_delta] DESC, [io_stall_delta] desc) )\n\t\t\t\t\t\t\t\t  ) / (SUM ([read_writes_delta]) OVER (PARTITION BY [collection_time_utc])) )\n\tFROM dbo.[vw_file_io_stats_deltas] AS [Stats]\n\tWHERE collection_time_utc between @start_time_utc and @end_time_utc\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND [Stats].[database_name] = @database\n  \"+(case when @disk_drive is null then '-- ' else '' end)+\"and [Stats].disk_volume = @disk_drive\n)\nSELECT\ttime = [collection_time_utc]\n\t\t--,[database_name]\n\t\t,[metric] =  [database_name]+ ' (__ '+[file_logical_name]+' __)'\n\t\t--,[file_logical_name]\n\t\t--,[file_location]\n\t\t--,[sample_ms_delta]\n\t\t--,[read_write_bytes_delta]\n\t\t--,[read_bytes_delta]\n\t\t--,[writes_bytes_delta]\n\t\t--,[StatsRank]\n\t\t--,[Percentage]\n\t\t--,[PercentageTotal]\n\t\t,[value] = [read_writes_delta]\nFROM [Stats] as cur\nWHERE [StatsRank] <= @FileIOStatsTop\nAND [PercentageTotal] <= @StatsPercentTop\nORDER BY [time] ASC, [read_writes_delta] DESC, [io_stall_delta] DESC\nOPTION(RECOMPILE);\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @perfmon_host_name, @start_time_utc, @end_time_utc, @disk_drive, @database;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @perfmon_host_name, @start_time_utc, @end_time_utc, @disk_drive, @database;"
      }
     ]
    }
   ]
  },
  {
   "title": "Database IO Stats - Since Startup__till____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - \"__${sql_schedulers} CPUs__\"  - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database IO Stats ____Since Startup ___ till ___ ${collection_time_utc:date:YYYY-MM-DD HH.mm}___",
     "type": "table",
     "description": "exec sp_BlitzFirst @seconds = 60, @ExpertMode = 1",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n--declare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\ndeclare @disk_drive varchar(255) = '$disk_drive';\ndeclare @database varchar(255) = '$database';\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @disk_drive = case when ltrim(rtrim(@disk_drive)) = '__All__' then null else @disk_drive end;\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n--set @delta_minutes = $cpu_delta_minutes;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @disk_drive varchar(255), @database varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - File IO Stats Since Startup */\nset nocount on;\ndeclare @start_time datetime;\ndeclare @schedulers smallint;\ndeclare @cpu_time_min decimal(18,1);\ndeclare @IOStatsTop tinyint = 10;\ndeclare @IOPercentTop int = 99;\n\nselect @start_time = sqlserver_start_time from sys.dm_os_sys_info;\nselect @schedulers = count(*) from sys.dm_os_schedulers where status = 'VISIBLE ONLINE' and is_online = 1;\n-- @cpu_time_min = sum(total_cpu_usage_ms/1000.0)/60.0\n\n;WITH [t_DiskDrives] AS (\n\tselect ds.disk_volume,ds.capacity_mb, ds.free_mb\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\t\"+(case when @disk_drive is null then '-- ' else '' end)+\"and ds.disk_volume = @disk_drive\n)\n,[t_FileIO] AS\n\t(\tSELECT\n\t\t\t[running_query] = 'File IO Stats', [collection_time_utc], [sample_ms], [database_name], \n\t\t\t[file_name_DISPLAY] = [file_logical_name]+' '+QUOTENAME(case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end),\n\t\t\t[file_logical_name], [file_location], [size_on_disk_bytes],\n\t\t\t[file_type] = case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end,\n\n\t\t\t[total_reads_writes] = [num_of_reads] + [num_of_writes], \n\t\t\t[num_of_bytes_read], [num_of_bytes_written], \n\t\t\t[total_reads_writes_bytes] = [num_of_bytes_read]+[num_of_bytes_written],\n\t\t\t\n\t\t\t[reads_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[writes_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)) + ' / ' + convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)),\n\n\t\t\t--[num_of_reads], [io_stall_read_ms], [num_of_writes],  [io_stall_write_ms],\n\t\t\t--[io_stall], [io_pending_ms_ticks_total],\n\t\t\t\n\t\t\t[read_latency_ms] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else (([io_stall_read_ms] * 1.0)/[num_of_reads]) end),\n\t\t\t[write_latency_ms] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else (([io_stall_write_ms] * 1.0)/[num_of_writes]) end),\n\t\t\t[latency_ms] = convert(numeric(20,2), case when [num_of_reads] + [num_of_writes] = 0 then 0 else (([io_stall] * 1.0) / ([num_of_reads] + [num_of_writes])) end),\n\n\t\t\t[avg_bytes_per_read] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else ( ([num_of_bytes_read] * 1.0) / [num_of_reads] ) end),\n\t\t\t[avg_bytes_per_write] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else ( ([num_of_bytes_written] * 1.0) / [num_of_writes] ) end),\n\t\t\t[avg_bytes_per_transfer] = convert(numeric(20,2), case when [num_of_reads] = 0 and [num_of_writes] = 0 then 0 else ( (([num_of_bytes_read]+[num_of_bytes_written]) * 1.0) / ([num_of_reads]+[num_of_writes]) ) end),\n\t\t\t\n\t\t\tdv.disk_volume, dv.capacity_mb, dv.free_mb\n\t\t\t\n\t\tFROM dbo.file_io_stats fis\n\t\tCROSS APPLY (\n\t\t\t\tselect top 1 *\n\t\t\t\tfrom [t_DiskDrives] dd\n\t\t\t\twhere fis.file_location like (dd.disk_volume+'%')\n\t\t\t\torder by len(dd.disk_volume) desc\n\t\t\t) dv\n\t\tWHERE fis.collection_time_utc = (SELECT MAX(i.collection_time_utc) FROM dbo.file_io_stats i)\n\t\t\"+(case when @database is null then '-- ' else '' end)+\"AND fis.[database_name] = @database\n    )\nselect\t[running_query] = max(running_query),\n\t\t[collection_time_utc] = max(collection_time_utc),\n\t\t[sample_ms] = max(sample_ms),\n\t\t[database_name],\n\t\t[files_count] = count(*),\n\t\t[disk_volume_count] = count(distinct disk_volume),\n\t\t[capacity_mb] = max(capacity_mb), \n\t\t[free_mb] = max(free_mb),\n\t\t[db_files_size_on_disk_mb] = convert(numeric(20,2),sum(size_on_disk_bytes*1.0/1024/1024)),\n\t\t[total_reads_writes] = sum(total_reads_writes),\n\t\t[reads_mb] = convert(numeric(20,2),sum(num_of_bytes_read)/1024.0/1024),\n\t\t[writes_mb] = convert(numeric(20,2),sum(num_of_bytes_written)/1024.0/1024),\n\t\t[reads_writes_mb] = convert(numeric(20,2),sum(num_of_bytes_read+num_of_bytes_written)/1024.0/1024),\n\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),(sum(num_of_bytes_read)*100.0/sum(num_of_bytes_read+num_of_bytes_written)))) \n\t\t\t\t\t\t\t\t+ ' / ' + \n\t\t\t\t\t\t\t\tconvert(varchar,convert(numeric(20,2),(sum(num_of_bytes_written)*100.0/sum(num_of_bytes_read+num_of_bytes_written))))\nfrom [t_FileIO] fio\ngroup by [database_name]\norder by [reads_writes_mb] desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;"
      }
     ]
    }
   ]
  },
  {
   "title": "Database IO Stats - Selective - \"__${sql_schedulers} CPUs__\" @ ${collection_time_utc:date:YYYY-MM-DD HH.mm}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database IO Stats ____Since Startup ___ till ___ ${__from:date:YYYY-MM-DD HH.mm}___",
     "type": "table",
     "description": "exec sp_BlitzFirst @seconds = 60, @ExpertMode = 1",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\ndeclare @disk_drive varchar(255) = '$disk_drive';\ndeclare @database varchar(255) = '$database';\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\n--set @start_time_utc = $__timeFrom();\nset @start_time_utc = dateadd(second,$sqlserver_start_time_utc/1000,'1970-01-01 00:00:00');\n--set @end_time_utc = $__timeTo();\nset @end_time_utc = $__timeFrom();\n--select @start_time_utc as start_time, @end_time_utc as end_time;\n--set @delta_minutes = $cpu_delta_minutes;\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @disk_drive = case when ltrim(rtrim(@disk_drive)) = '__All__' then null else @disk_drive end;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @disk_drive varchar(255), @database varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - File IO Stats Since Startup */\nset nocount on;\ndeclare @start_time datetime;\ndeclare @schedulers smallint;\ndeclare @cpu_time_min decimal(18,1);\ndeclare @IOStatsTop tinyint = 10;\ndeclare @IOPercentTop int = 99;\n\nselect @start_time = sqlserver_start_time from sys.dm_os_sys_info;\nselect @schedulers = count(*) from sys.dm_os_schedulers where status = 'VISIBLE ONLINE' and is_online = 1;\n-- @cpu_time_min = sum(total_cpu_usage_ms/1000.0)/60.0\n\n;WITH [t_DiskDrives] AS (\n\tselect ds.disk_volume,ds.capacity_mb, ds.free_mb\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\t\"+(case when @disk_drive is null then '-- ' else '' end)+\"and ds.disk_volume = @disk_drive\n)\n,[t_FileIO] AS\n\t(\tSELECT\n\t\t\t[running_query] = 'File IO Stats', [collection_time_utc], [sample_ms], [database_name], \n\t\t\t[file_name_DISPLAY] = [file_logical_name]+' '+QUOTENAME(case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end),\n\t\t\t[file_logical_name], [file_location], [size_on_disk_bytes],\n\t\t\t[file_type] = case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end,\n\n\t\t\t[total_reads_writes] = [num_of_reads] + [num_of_writes], \n\t\t\t[num_of_bytes_read], [num_of_bytes_written], \n\t\t\t[total_reads_writes_bytes] = [num_of_bytes_read]+[num_of_bytes_written],\n\t\t\t\n\t\t\t[reads_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[writes_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)) + ' / ' + convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)),\n\n\t\t\t--[num_of_reads], [io_stall_read_ms], [num_of_writes],  [io_stall_write_ms],\n\t\t\t--[io_stall], [io_pending_ms_ticks_total],\n\t\t\t\n\t\t\t[read_latency_ms] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else (([io_stall_read_ms] * 1.0)/[num_of_reads]) end),\n\t\t\t[write_latency_ms] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else (([io_stall_write_ms] * 1.0)/[num_of_writes]) end),\n\t\t\t[latency_ms] = convert(numeric(20,2), case when [num_of_reads] + [num_of_writes] = 0 then 0 else (([io_stall] * 1.0) / ([num_of_reads] + [num_of_writes])) end),\n\n\t\t\t[avg_bytes_per_read] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else ( ([num_of_bytes_read] * 1.0) / [num_of_reads] ) end),\n\t\t\t[avg_bytes_per_write] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else ( ([num_of_bytes_written] * 1.0) / [num_of_writes] ) end),\n\t\t\t[avg_bytes_per_transfer] = convert(numeric(20,2), case when [num_of_reads] = 0 and [num_of_writes] = 0 then 0 else ( (([num_of_bytes_read]+[num_of_bytes_written]) * 1.0) / ([num_of_reads]+[num_of_writes]) ) end),\n\t\t\t\n\t\t\tdv.disk_volume, dv.capacity_mb, dv.free_mb\n\t\t\t\n\t\tFROM dbo.file_io_stats fis\n\t\tCROSS APPLY (\n\t\t\t\tselect top 1 *\n\t\t\t\tfrom [t_DiskDrives] dd\n\t\t\t\twhere fis.file_location like (dd.disk_volume+'%')\n\t\t\t\torder by len(dd.disk_volume) desc\n\t\t\t) dv\n\t\tWHERE fis.collection_time_utc = (SELECT MAX(i.collection_time_utc) FROM dbo.file_io_stats i WHERE i.collection_time_utc <= @end_time_utc)\n\t\t\"+(case when @database is null then '-- ' else '' end)+\"AND fis.[database_name] = @database\n    )\nselect\t[running_query] = max(running_query),\n\t\t[collection_time_utc] = max(collection_time_utc),\n\t\t[sample_ms] = max(sample_ms),\n\t\t[database_name],\n\t\t[files_count] = count(*),\n\t\t[disk_volume_count] = count(distinct disk_volume),\n\t\t[capacity_mb] = max(capacity_mb), \n\t\t[free_mb] = max(free_mb),\n\t\t[db_files_size_on_disk_mb] = convert(numeric(20,2),sum(size_on_disk_bytes*1.0/1024/1024)),\n\t\t[total_reads_writes] = sum(total_reads_writes),\n\t\t[reads_mb] = convert(numeric(20,2),sum(num_of_bytes_read)/1024.0/1024),\n\t\t[writes_mb] = convert(numeric(20,2),sum(num_of_bytes_written)/1024.0/1024),\n\t\t[reads_writes_mb] = convert(numeric(20,2),sum(num_of_bytes_read+num_of_bytes_written)/1024.0/1024),\n\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),(sum(num_of_bytes_read)*100.0/sum(num_of_bytes_read+num_of_bytes_written)))) \n\t\t\t\t\t\t\t\t+ ' / ' + \n\t\t\t\t\t\t\t\tconvert(varchar,convert(numeric(20,2),(sum(num_of_bytes_written)*100.0/sum(num_of_bytes_read+num_of_bytes_written))))\nfrom [t_FileIO] fio\ngroup by [database_name]\norder by [reads_writes_mb] desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;"
      }
     ]
    },
    {
     "title": "Database IO Stats ____In Selected Time Duration____Since____${__from:date:YYYY-MM-DD HH.mm}___till___${__to:date:YYYY-MM-DD HH.mm}____",
     "type": "table",
     "description": "exec sp_BlitzFirst @seconds = 60, @ExpertMode = 1",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n--declare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\ndeclare @disk_drive varchar(255) = '$disk_drive';\ndeclare @database varchar(255) = '$database';\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @disk_drive = case when ltrim(rtrim(@disk_drive)) = '__All__' then null else @disk_drive end;\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n--set @delta_minutes = $cpu_delta_minutes;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @disk_drive varchar(255), @database varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"\nset nocount on;\ndeclare @schedulers smallint;\ndeclare @StatstatsTop tinyint = 10;\ndeclare @StatsPercentTop int = 99;\ndeclare @collect_time_utc_snap1 datetime2;\ndeclare @collect_time_utc_snap2 datetime2;\n\n--select @start_time_utc = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), sqlserver_start_time) from sys.dm_os_sys_info;\nselect @schedulers = count(*) from sys.dm_os_schedulers where status = 'VISIBLE ONLINE' and is_online = 1;\n\nselect top 1 @collect_time_utc_snap2 = collection_time_utc\nfrom dbo.file_io_stats s2\nwhere s2.collection_time_utc <= @end_time_utc\norder by collection_time_utc desc;\n\nselect top 1 @collect_time_utc_snap1 = collection_time_utc\nfrom dbo.file_io_stats s1\nwhere collection_time_utc >= @start_time_utc\norder by collection_time_utc asc;\n\n--select @collect_time_utc_snap1, @collect_time_utc_snap2;\n\n;WITH [DiffStats] AS\n(\tSELECT\t-- Stats that weren't in the first snapshot\n\t\t\t--[ts2].[collection_time_utc],\n\t\t\t[ts2].[database_name],\n\t\t\t[ts2].[database_id],\n\t\t\t[ts2].[file_logical_name],\n\t\t\t[ts2].[file_id],\n\t\t\t[ts2].[file_location],\n\t\t\t[ts2].[sample_ms],\n\t\t\t[ts2].[num_of_reads],\n\t\t\t[ts2].[num_of_bytes_read],\n\t\t\t[ts2].[io_stall_read_ms],\n\t\t\t[ts2].[io_stall_queued_read_ms],\n\t\t\t[ts2].[num_of_writes],\n\t\t\t[ts2].[num_of_bytes_written],\n\t\t\t[ts2].[io_stall_write_ms],\n\t\t\t[ts2].[io_stall_queued_write_ms],\n\t\t\t[ts2].[io_stall],\n\t\t\t[ts2].[size_on_disk_bytes],\n\t\t\t[ts2].[io_pending_count]\n\tFROM dbo.file_io_stats AS [ts2]\n\tLEFT OUTER JOIN dbo.file_io_stats AS [ts1]\n\t\tON [ts2].[database_name] = [ts1].[database_name]\n\t\tAND [ts2].[file_logical_name] = [ts1].[file_logical_name]\n\t\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\tAND [ts1].collection_time_utc = @collect_time_utc_snap1\n\tWHERE [ts1].[file_logical_name] IS NULL\n\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts1.[database_name] = @database\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts2.[database_name] = @database\n\t--\n\tUNION\n\t--\n\tSELECT\t-- Diff of Stats in both snapshots\n\t\t\t--[collection_time_utc] = [ts2].[collection_time_utc] - [ts1].[collection_time_utc],\n\t\t\t[database_name] = [ts2].[database_name],\n\t\t\t[database_id] = [ts2].[database_id],\n\t\t\t[file_logical_name] = [ts2].[file_logical_name],\n\t\t\t[file_id] = [ts2].[file_id],\n\t\t\t[file_location] = [ts2].[file_location],\n\t\t\t[sample_ms] = [ts2].[sample_ms] - [ts1].[sample_ms],\n\t\t\t[num_of_reads] = [ts2].[num_of_reads] - [ts1].[num_of_reads],\n\t\t\t[num_of_bytes_read] = [ts2].[num_of_bytes_read] - [ts1].[num_of_bytes_read],\n\t\t\t[io_stall_read_ms] = [ts2].[io_stall_read_ms] - [ts1].[io_stall_read_ms],\n\t\t\t[io_stall_queued_read_ms] = [ts2].[io_stall_queued_read_ms] - [ts1].[io_stall_queued_read_ms],\n\t\t\t[num_of_writes] = [ts2].[num_of_writes] - [ts1].[num_of_writes],\n\t\t\t[num_of_bytes_written] = [ts2].[num_of_bytes_written] - [ts1].[num_of_bytes_written],\n\t\t\t[io_stall_write_ms] = [ts2].[io_stall_write_ms] - [ts1].[io_stall_write_ms],\n\t\t\t[io_stall_queued_write_ms] = [ts2].[io_stall_queued_write_ms] - [ts1].[io_stall_queued_write_ms],\n\t\t\t[io_stall] = [ts2].[io_stall] - [ts1].[io_stall],\n\t\t\t[size_on_disk_bytes] = [ts2].[size_on_disk_bytes],\n\t\t\t[io_pending_count] = [ts2].[io_pending_count] - [ts1].[io_pending_count]\n\tFROM dbo.file_io_stats AS [ts2]\n\tLEFT OUTER JOIN dbo.file_io_stats AS [ts1]\n\t\tON [ts2].[database_name] = [ts1].[database_name]\n\t\tAND [ts2].[file_logical_name] = [ts1].[file_logical_name]\n\t\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\tAND [ts1].collection_time_utc = @collect_time_utc_snap1\n\tWHERE [ts1].[file_logical_name] IS NOT NULL\n\tAND ( ([ts2].[num_of_reads]+[ts2].[num_of_writes]) - ([ts1].[num_of_reads]+[ts1].[num_of_writes]) ) > 0\n\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts1.[database_name] = @database\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts2.[database_name] = @database\n)\n,[t_DiskDrives] AS \n(\tselect ds.disk_volume, ds.capacity_mb, ds.free_mb\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\t\"+(case when @disk_drive is null then '-- ' else '' end)+\"and ds.disk_volume = @disk_drive\n)\n,[t_FileIO] AS\n(\tSELECT\t[running_query] = 'File IO Stats', [sample_ms], [database_name], \n\t\t\t[file_name_DISPLAY] = [file_logical_name]+' '+QUOTENAME(case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end),\n\t\t\t[file_logical_name], [file_location], dv.disk_volume, [size_on_disk_bytes],\n\t\t\t[file_type] = case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end,\n\n\t\t\t[total_reads_writes] = [num_of_reads] + [num_of_writes], \n\t\t\t[num_of_bytes_read], [num_of_bytes_written], \n\t\t\t[total_reads_writes_bytes] = [num_of_bytes_read]+[num_of_bytes_written],\n\t\t\t\n\t\t\t[reads_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[writes_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)) + ' / ' + convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)),\n\n\t\t\t--[num_of_reads], [io_stall_read_ms], [num_of_writes],  [io_stall_write_ms],\n\t\t\t--[io_stall], [io_pending_ms_ticks_total],\n\t\t\t\n\t\t\t[read_latency_ms] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else (([io_stall_read_ms] * 1.0)/[num_of_reads]) end),\n\t\t\t[write_latency_ms] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else (([io_stall_write_ms] * 1.0)/[num_of_writes]) end),\n\t\t\t[latency_ms] = convert(numeric(20,2), case when [num_of_reads] + [num_of_writes] = 0 then 0 else (([io_stall] * 1.0) / ([num_of_reads] + [num_of_writes])) end),\n\n\t\t\t[avg_bytes_per_read] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else ( ([num_of_bytes_read] * 1.0) / [num_of_reads] ) end),\n\t\t\t[avg_bytes_per_write] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else ( ([num_of_bytes_written] * 1.0) / [num_of_writes] ) end),\n\t\t\t[avg_bytes_per_transfer] = convert(numeric(20,2), case when [num_of_reads] = 0 and [num_of_writes] = 0 then 0 else ( (([num_of_bytes_read]+[num_of_bytes_written]) * 1.0) / ([num_of_reads]+[num_of_writes]) ) end)\n\tFROM [DiffStats] fis\n\tCROSS APPLY (\n\t\t\tselect top 1 dd.*\n\t\t\tfrom [t_DiskDrives] dd\n\t\t\twhere fis.file_location like (dd.disk_volume+'%')\n\t\t\torder by len(dd.disk_volume) desc\n\t\t) dv\n)\nselect\t[running_query] = max(running_query),\n\t\t--[collection_time_utc] = max(collection_time_utc),\n\t\t[sample_ms] = max(sample_ms),\n\t\t[database_name],\n\t\t[files_count] = count(*),\n\t\t[disk_drive_count] = count(distinct dd.disk_volume),\n\t\t--[disk_volume] = max(dd.disk_volume), \n\t\t[capacity_mb] = max(dd.capacity_mb), \n\t\t[free_mb] = max(dd.free_mb),\n\t\t[db_files_size_on_disk_mb] = convert(numeric(20,2),sum(size_on_disk_bytes/1024.0/1024)),\n\t\t[total_reads_writes] = sum(total_reads_writes),\n\t\t[reads_mb] = convert(numeric(20,2),sum(num_of_bytes_read/1024.0/1024)),\n\t\t[writes_mb] = convert(numeric(20,2),sum(num_of_bytes_written/1024.0/1024)),\n\t\t[reads_writes_mb] = convert(numeric(20,2),sum( (num_of_bytes_read+num_of_bytes_written)/1024.0/1024 )),\n\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),(sum(num_of_bytes_read)*100.0/sum(num_of_bytes_read+num_of_bytes_written)))) \n\t\t\t\t\t\t\t\t+ ' / ' + \n\t\t\t\t\t\t\t\tconvert(varchar,convert(numeric(20,2),(sum(num_of_bytes_written)*100.0/sum(num_of_bytes_read+num_of_bytes_written))))\nfrom [t_FileIO] fio\nleft join [t_DiskDrives] dd on dd.disk_volume = fio.disk_volume\ngroup by database_name\norder by [reads_writes_mb] desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO Stats - Since Startup__till____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - \"__${sql_schedulers} CPUs__\"  - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IO Stats ____Since Startup ___ till ___ ${collection_time_utc:date:YYYY-MM-DD HH.mm}___",
     "type": "table",
     "description": "exec sp_BlitzFirst @seconds = 60, @ExpertMode = 1",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n--declare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\ndeclare @disk_drive varchar(255) = '$disk_drive';\ndeclare @database varchar(255) = '$database';\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @disk_drive = case when ltrim(rtrim(@disk_drive)) = '__All__' then null else @disk_drive end;\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n--set @delta_minutes = $cpu_delta_minutes;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @disk_drive varchar(255), @database varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - File IO Stats Since Startup */\nset nocount on;\ndeclare @start_time datetime;\ndeclare @schedulers smallint;\ndeclare @cpu_time_min decimal(18,1);\ndeclare @IOStatsTop tinyint = 10;\ndeclare @IOPercentTop int = 99;\n\nselect @start_time = sqlserver_start_time from sys.dm_os_sys_info;\nselect @schedulers = count(*) from sys.dm_os_schedulers where status = 'VISIBLE ONLINE' and is_online = 1;\n-- @cpu_time_min = sum(total_cpu_usage_ms/1000.0)/60.0\n\n;WITH [t_DiskDrives] AS (\n\tselect ds.disk_volume,ds.capacity_mb, ds.free_mb\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\t\"+(case when @disk_drive is null then '-- ' else '' end)+\"and ds.disk_volume = @disk_drive\n)\n,[t_FileIO] AS\n\t(\tSELECT\n\t\t\t[running_query] = 'File IO Stats', [collection_time_utc], [sample_ms], [database_name], \n\t\t\t[file_name_DISPLAY] = [file_logical_name]+' '+QUOTENAME(case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end),\n\t\t\t[file_logical_name], [file_location], [size_on_disk_bytes],\n\t\t\t[file_type] = case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end,\n\n\t\t\t[total_reads_writes] = [num_of_reads] + [num_of_writes], \n\t\t\t[num_of_bytes_read], [num_of_bytes_written], \n\t\t\t[total_reads_writes_bytes] = [num_of_bytes_read]+[num_of_bytes_written],\n\t\t\t\n\t\t\t[reads_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[writes_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)) + ' / ' + convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)),\n\n\t\t\t--[num_of_reads], [io_stall_read_ms], [num_of_writes],  [io_stall_write_ms],\n\t\t\t--[io_stall], [io_pending_ms_ticks_total],\n\t\t\t\n\t\t\t[read_latency_ms] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else (([io_stall_read_ms] * 1.0)/[num_of_reads]) end),\n\t\t\t[write_latency_ms] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else (([io_stall_write_ms] * 1.0)/[num_of_writes]) end),\n\t\t\t[latency_ms] = convert(numeric(20,2), case when [num_of_reads] + [num_of_writes] = 0 then 0 else (([io_stall] * 1.0) / ([num_of_reads] + [num_of_writes])) end),\n\n\t\t\t[avg_bytes_per_read] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else ( ([num_of_bytes_read] * 1.0) / [num_of_reads] ) end),\n\t\t\t[avg_bytes_per_write] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else ( ([num_of_bytes_written] * 1.0) / [num_of_writes] ) end),\n\t\t\t[avg_bytes_per_transfer] = convert(numeric(20,2), case when [num_of_reads] = 0 and [num_of_writes] = 0 then 0 else ( (([num_of_bytes_read]+[num_of_bytes_written]) * 1.0) / ([num_of_reads]+[num_of_writes]) ) end),\n\t\t\t\n\t\t\tdv.disk_volume, dv.capacity_mb, dv.free_mb\n\t\t\t\n\t\tFROM dbo.file_io_stats fis\n\t\tCROSS APPLY (\n\t\t\t\tselect top 1 *\n\t\t\t\tfrom [t_DiskDrives] dd\n\t\t\t\twhere fis.file_location like (dd.disk_volume+'%')\n\t\t\t\torder by len(dd.disk_volume) desc\n\t\t\t) dv\n\t\tWHERE fis.collection_time_utc = (SELECT MAX(i.collection_time_utc) FROM dbo.file_io_stats i)\n\t\t\"+(case when @database is null then '-- ' else '' end)+\"AND fis.[database_name] = @database\n    )\nselect\t[running_query] = max(running_query),\n\t\t[collection_time_utc] = max(collection_time_utc),\n\t\t[sample_ms] = max(sample_ms),\n\t\t[database_count] = count(distinct database_name),\n\t\t[files_count] = count(*),\n\t\t[disk_volume] = max(disk_volume), \n\t\t[capacity_mb] = max(capacity_mb), \n\t\t[free_mb] = max(free_mb),\n\t\t[db_files_size_on_disk_mb] = convert(numeric(20,2),sum(size_on_disk_bytes*1.0/1024/1024)),\n\t\t[total_reads_writes] = sum(total_reads_writes),\n\t\t[reads_mb] = convert(numeric(20,2),sum(num_of_bytes_read)/1024.0/1024),\n\t\t[writes_mb] = convert(numeric(20,2),sum(num_of_bytes_written)/1024.0/1024),\n\t\t[reads_writes_mb] = convert(numeric(20,2),sum(num_of_bytes_read+num_of_bytes_written)/1024.0/1024),\n\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),(sum(num_of_bytes_read)*100.0/sum(num_of_bytes_read+num_of_bytes_written)))) \n\t\t\t\t\t\t\t\t+ ' / ' + \n\t\t\t\t\t\t\t\tconvert(varchar,convert(numeric(20,2),(sum(num_of_bytes_written)*100.0/sum(num_of_bytes_read+num_of_bytes_written))))\nfrom [t_FileIO] fio\ngroup by disk_volume\norder by [reads_writes_mb] desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO Stats - Selective - \"__${sql_schedulers} CPUs__\" @ ${collection_time_utc:date:YYYY-MM-DD HH.mm}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IO Stats ____Since Startup ___ till ___ ${__from:date:YYYY-MM-DD HH.mm}___",
     "type": "table",
     "description": "exec sp_BlitzFirst @seconds = 60, @ExpertMode = 1",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\ndeclare @disk_drive varchar(255) = '$disk_drive';\ndeclare @database varchar(255) = '$database';\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @disk_drive = case when ltrim(rtrim(@disk_drive)) = '__All__' then null else @disk_drive end;\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\n--set @start_time_utc = $__timeFrom();\nset @start_time_utc = dateadd(second,$sqlserver_start_time_utc/1000,'1970-01-01 00:00:00');\n--set @end_time_utc = $__timeTo();\nset @end_time_utc = $__timeFrom();\n--select @start_time_utc as start_time, @end_time_utc as end_time;\n--set @delta_minutes = $cpu_delta_minutes;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @disk_drive varchar(255), @database varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"\nset nocount on;\ndeclare @schedulers smallint;\ndeclare @StatstatsTop tinyint = 10;\ndeclare @StatsPercentTop int = 99;\ndeclare @collect_time_utc_snap1 datetime2;\ndeclare @collect_time_utc_snap2 datetime2;\n\n--select @start_time_utc = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), sqlserver_start_time) from sys.dm_os_sys_info;\nselect @schedulers = count(*) from sys.dm_os_schedulers where status = 'VISIBLE ONLINE' and is_online = 1;\n\nselect top 1 @collect_time_utc_snap2 = collection_time_utc\nfrom dbo.file_io_stats s2\nwhere s2.collection_time_utc <= @end_time_utc\norder by collection_time_utc desc;\n\nselect top 1 @collect_time_utc_snap1 = collection_time_utc\nfrom dbo.file_io_stats s1\nwhere collection_time_utc >= @start_time_utc\norder by collection_time_utc asc;\n\n--select @collect_time_utc_snap1, @collect_time_utc_snap2;\n\n;WITH [DiffStats] AS\n(\tSELECT\t-- Stats that weren't in the first snapshot\n\t\t\t--[ts2].[collection_time_utc],\n\t\t\t[ts2].[database_name],\n\t\t\t[ts2].[database_id],\n\t\t\t[ts2].[file_logical_name],\n\t\t\t[ts2].[file_id],\n\t\t\t[ts2].[file_location],\n\t\t\t[ts2].[sample_ms],\n\t\t\t[ts2].[num_of_reads],\n\t\t\t[ts2].[num_of_bytes_read],\n\t\t\t[ts2].[io_stall_read_ms],\n\t\t\t[ts2].[io_stall_queued_read_ms],\n\t\t\t[ts2].[num_of_writes],\n\t\t\t[ts2].[num_of_bytes_written],\n\t\t\t[ts2].[io_stall_write_ms],\n\t\t\t[ts2].[io_stall_queued_write_ms],\n\t\t\t[ts2].[io_stall],\n\t\t\t[ts2].[size_on_disk_bytes],\n\t\t\t[ts2].[io_pending_count]\n\tFROM dbo.file_io_stats AS [ts2]\n\tLEFT OUTER JOIN dbo.file_io_stats AS [ts1]\n\t\tON [ts2].[database_name] = [ts1].[database_name]\n\t\tAND [ts2].[file_logical_name] = [ts1].[file_logical_name]\n\t\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\tAND [ts1].collection_time_utc = @collect_time_utc_snap1\n\tWHERE [ts1].[file_logical_name] IS NULL\n\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts1.[database_name] = @database\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts2.[database_name] = @database\n\t--\n\tUNION\n\t--\n\tSELECT\t-- Diff of Stats in both snapshots\n\t\t\t--[collection_time_utc] = [ts2].[collection_time_utc] - [ts1].[collection_time_utc],\n\t\t\t[database_name] = [ts2].[database_name],\n\t\t\t[database_id] = [ts2].[database_id],\n\t\t\t[file_logical_name] = [ts2].[file_logical_name],\n\t\t\t[file_id] = [ts2].[file_id],\n\t\t\t[file_location] = [ts2].[file_location],\n\t\t\t[sample_ms] = [ts2].[sample_ms] - [ts1].[sample_ms],\n\t\t\t[num_of_reads] = [ts2].[num_of_reads] - [ts1].[num_of_reads],\n\t\t\t[num_of_bytes_read] = [ts2].[num_of_bytes_read] - [ts1].[num_of_bytes_read],\n\t\t\t[io_stall_read_ms] = [ts2].[io_stall_read_ms] - [ts1].[io_stall_read_ms],\n\t\t\t[io_stall_queued_read_ms] = [ts2].[io_stall_queued_read_ms] - [ts1].[io_stall_queued_read_ms],\n\t\t\t[num_of_writes] = [ts2].[num_of_writes] - [ts1].[num_of_writes],\n\t\t\t[num_of_bytes_written] = [ts2].[num_of_bytes_written] - [ts1].[num_of_bytes_written],\n\t\t\t[io_stall_write_ms] = [ts2].[io_stall_write_ms] - [ts1].[io_stall_write_ms],\n\t\t\t[io_stall_queued_write_ms] = [ts2].[io_stall_queued_write_ms] - [ts1].[io_stall_queued_write_ms],\n\t\t\t[io_stall] = [ts2].[io_stall] - [ts1].[io_stall],\n\t\t\t[size_on_disk_bytes] = [ts2].[size_on_disk_bytes],\n\t\t\t[io_pending_count] = [ts2].[io_pending_count] - [ts1].[io_pending_count]\n\tFROM dbo.file_io_stats AS [ts2]\n\tLEFT OUTER JOIN dbo.file_io_stats AS [ts1]\n\t\tON [ts2].[database_name] = [ts1].[database_name]\n\t\tAND [ts2].[file_logical_name] = [ts1].[file_logical_name]\n\t\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\tAND [ts1].collection_time_utc = @collect_time_utc_snap1\n\tWHERE [ts1].[file_logical_name] IS NOT NULL\n\tAND ( ([ts2].[num_of_reads]+[ts2].[num_of_writes]) - ([ts1].[num_of_reads]+[ts1].[num_of_writes]) ) > 0\n\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts1.[database_name] = @database\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts2.[database_name] = @database\n)\n,[t_DiskDrives] AS \n(\tselect ds.disk_volume, ds.capacity_mb, ds.free_mb\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\t\"+(case when @disk_drive is null then '-- ' else '' end)+\"and ds.disk_volume = @disk_drive\n)\n,[t_FileIO] AS\n(\tSELECT\t[running_query] = 'File IO Stats', [sample_ms], [database_name], \n\t\t\t[file_name_DISPLAY] = [file_logical_name]+' '+QUOTENAME(case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end),\n\t\t\t[file_logical_name], [file_location], dv.disk_volume, [size_on_disk_bytes],\n\t\t\t[file_type] = case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end,\n\n\t\t\t[total_reads_writes] = [num_of_reads] + [num_of_writes], \n\t\t\t[num_of_bytes_read], [num_of_bytes_written], \n\t\t\t[total_reads_writes_bytes] = [num_of_bytes_read]+[num_of_bytes_written],\n\t\t\t\n\t\t\t[reads_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[writes_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)) + ' / ' + convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)),\n\n\t\t\t--[num_of_reads], [io_stall_read_ms], [num_of_writes],  [io_stall_write_ms],\n\t\t\t--[io_stall], [io_pending_ms_ticks_total],\n\t\t\t\n\t\t\t[read_latency_ms] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else (([io_stall_read_ms] * 1.0)/[num_of_reads]) end),\n\t\t\t[write_latency_ms] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else (([io_stall_write_ms] * 1.0)/[num_of_writes]) end),\n\t\t\t[latency_ms] = convert(numeric(20,2), case when [num_of_reads] + [num_of_writes] = 0 then 0 else (([io_stall] * 1.0) / ([num_of_reads] + [num_of_writes])) end),\n\n\t\t\t[avg_bytes_per_read] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else ( ([num_of_bytes_read] * 1.0) / [num_of_reads] ) end),\n\t\t\t[avg_bytes_per_write] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else ( ([num_of_bytes_written] * 1.0) / [num_of_writes] ) end),\n\t\t\t[avg_bytes_per_transfer] = convert(numeric(20,2), case when [num_of_reads] = 0 and [num_of_writes] = 0 then 0 else ( (([num_of_bytes_read]+[num_of_bytes_written]) * 1.0) / ([num_of_reads]+[num_of_writes]) ) end)\n\tFROM [DiffStats] fis\n\tCROSS APPLY (\n\t\t\tselect top 1 dd.*\n\t\t\tfrom [t_DiskDrives] dd\n\t\t\twhere fis.file_location like (dd.disk_volume+'%')\n\t\t\torder by len(dd.disk_volume) desc\n\t\t) dv\n)\nselect\t[running_query] = max(running_query),\n\t\t--[collection_time_utc] = max(collection_time_utc),\n\t\t[sample_ms] = max(sample_ms),\n\t\t[database_count] = count(distinct database_name),\n\t\t[files_count] = count(*),\n\t\t[disk_volume] = max(dd.disk_volume), \n\t\t[capacity_mb] = max(dd.capacity_mb), \n\t\t[free_mb] = max(dd.free_mb),\n\t\t[db_files_size_on_disk_mb] = convert(numeric(20,2),sum(size_on_disk_bytes/1024.0/1024)),\n\t\t[total_reads_writes] = sum(total_reads_writes),\n\t\t[reads_mb] = convert(numeric(20,2),sum(num_of_bytes_read/1024.0/1024)),\n\t\t[writes_mb] = convert(numeric(20,2),sum(num_of_bytes_written/1024.0/1024)),\n\t\t[reads_writes_mb] = convert(numeric(20,2),sum( (num_of_bytes_read+num_of_bytes_written)/1024.0/1024 )),\n\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),(sum(num_of_bytes_read)*100.0/sum(num_of_bytes_read+num_of_bytes_written)))) \n\t\t\t\t\t\t\t\t+ ' / ' + \n\t\t\t\t\t\t\t\tconvert(varchar,convert(numeric(20,2),(sum(num_of_bytes_written)*100.0/sum(num_of_bytes_read+num_of_bytes_written))))\nfrom [t_FileIO] fio\nleft join [t_DiskDrives] dd on dd.disk_volume = fio.disk_volume\ngroup by dd.disk_volume\norder by [reads_writes_mb] desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;"
      }
     ]
    },
    {
     "title": "Disk IO Stats ____In Selected Time Duration____Since____${__from:date:YYYY-MM-DD HH.mm}___till___${__to:date:YYYY-MM-DD HH.mm}____",
     "type": "table",
     "description": "exec sp_BlitzFirst @seconds = 60, @ExpertMode = 1",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n--declare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\ndeclare @disk_drive varchar(255) = '$disk_drive';\ndeclare @database varchar(255) = '$database';\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @disk_drive = case when ltrim(rtrim(@disk_drive)) = '__All__' then null else @disk_drive end;\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n--set @delta_minutes = $cpu_delta_minutes;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @disk_drive varchar(255), @database varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"\nset nocount on;\ndeclare @schedulers smallint;\ndeclare @StatstatsTop tinyint = 10;\ndeclare @StatsPercentTop int = 99;\ndeclare @collect_time_utc_snap1 datetime2;\ndeclare @collect_time_utc_snap2 datetime2;\n\n--select @start_time_utc = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), sqlserver_start_time) from sys.dm_os_sys_info;\nselect @schedulers = count(*) from sys.dm_os_schedulers where status = 'VISIBLE ONLINE' and is_online = 1;\n\nselect top 1 @collect_time_utc_snap2 = collection_time_utc\nfrom dbo.file_io_stats s2\nwhere s2.collection_time_utc <= @end_time_utc\norder by collection_time_utc desc;\n\nselect top 1 @collect_time_utc_snap1 = collection_time_utc\nfrom dbo.file_io_stats s1\nwhere collection_time_utc >= @start_time_utc\norder by collection_time_utc asc;\n\n--select @collect_time_utc_snap1, @collect_time_utc_snap2;\n\n;WITH [DiffStats] AS\n(\tSELECT\t-- Stats that weren't in the first snapshot\n\t\t\t--[ts2].[collection_time_utc],\n\t\t\t[ts2].[database_name],\n\t\t\t[ts2].[database_id],\n\t\t\t[ts2].[file_logical_name],\n\t\t\t[ts2].[file_id],\n\t\t\t[ts2].[file_location],\n\t\t\t[ts2].[sample_ms],\n\t\t\t[ts2].[num_of_reads],\n\t\t\t[ts2].[num_of_bytes_read],\n\t\t\t[ts2].[io_stall_read_ms],\n\t\t\t[ts2].[io_stall_queued_read_ms],\n\t\t\t[ts2].[num_of_writes],\n\t\t\t[ts2].[num_of_bytes_written],\n\t\t\t[ts2].[io_stall_write_ms],\n\t\t\t[ts2].[io_stall_queued_write_ms],\n\t\t\t[ts2].[io_stall],\n\t\t\t[ts2].[size_on_disk_bytes],\n\t\t\t[ts2].[io_pending_count]\n\tFROM dbo.file_io_stats AS [ts2]\n\tLEFT OUTER JOIN dbo.file_io_stats AS [ts1]\n\t\tON [ts2].[database_name] = [ts1].[database_name]\n\t\tAND [ts2].[file_logical_name] = [ts1].[file_logical_name]\n\t\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\tAND [ts1].collection_time_utc = @collect_time_utc_snap1\n\tWHERE [ts1].[file_logical_name] IS NULL\n\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts1.[database_name] = @database\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts2.[database_name] = @database\n\t--\n\tUNION\n\t--\n\tSELECT\t-- Diff of Stats in both snapshots\n\t\t\t--[collection_time_utc] = [ts2].[collection_time_utc] - [ts1].[collection_time_utc],\n\t\t\t[database_name] = [ts2].[database_name],\n\t\t\t[database_id] = [ts2].[database_id],\n\t\t\t[file_logical_name] = [ts2].[file_logical_name],\n\t\t\t[file_id] = [ts2].[file_id],\n\t\t\t[file_location] = [ts2].[file_location],\n\t\t\t[sample_ms] = [ts2].[sample_ms] - [ts1].[sample_ms],\n\t\t\t[num_of_reads] = [ts2].[num_of_reads] - [ts1].[num_of_reads],\n\t\t\t[num_of_bytes_read] = [ts2].[num_of_bytes_read] - [ts1].[num_of_bytes_read],\n\t\t\t[io_stall_read_ms] = [ts2].[io_stall_read_ms] - [ts1].[io_stall_read_ms],\n\t\t\t[io_stall_queued_read_ms] = [ts2].[io_stall_queued_read_ms] - [ts1].[io_stall_queued_read_ms],\n\t\t\t[num_of_writes] = [ts2].[num_of_writes] - [ts1].[num_of_writes],\n\t\t\t[num_of_bytes_written] = [ts2].[num_of_bytes_written] - [ts1].[num_of_bytes_written],\n\t\t\t[io_stall_write_ms] = [ts2].[io_stall_write_ms] - [ts1].[io_stall_write_ms],\n\t\t\t[io_stall_queued_write_ms] = [ts2].[io_stall_queued_write_ms] - [ts1].[io_stall_queued_write_ms],\n\t\t\t[io_stall] = [ts2].[io_stall] - [ts1].[io_stall],\n\t\t\t[size_on_disk_bytes] = [ts2].[size_on_disk_bytes],\n\t\t\t[io_pending_count] = [ts2].[io_pending_count] - [ts1].[io_pending_count]\n\tFROM dbo.file_io_stats AS [ts2]\n\tLEFT OUTER JOIN dbo.file_io_stats AS [ts1]\n\t\tON [ts2].[database_name] = [ts1].[database_name]\n\t\tAND [ts2].[file_logical_name] = [ts1].[file_logical_name]\n\t\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\tAND [ts1].collection_time_utc = @collect_time_utc_snap1\n\tWHERE [ts1].[file_logical_name] IS NOT NULL\n\tAND ( ([ts2].[num_of_reads]+[ts2].[num_of_writes]) - ([ts1].[num_of_reads]+[ts1].[num_of_writes]) ) > 0\n\tAND [ts2].collection_time_utc = @collect_time_utc_snap2\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts1.[database_name] = @database\n\t\"+(case when @database is null then '-- ' else '' end)+\"AND ts2.[database_name] = @database\n)\n,[t_DiskDrives] AS \n(\tselect ds.disk_volume, ds.capacity_mb, ds.free_mb\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\t\"+(case when @disk_drive is null then '-- ' else '' end)+\"and ds.disk_volume = @disk_drive\n)\n,[t_FileIO] AS\n(\tSELECT\t[running_query] = 'File IO Stats', [sample_ms], [database_name], \n\t\t\t[file_name_DISPLAY] = [file_logical_name]+' '+QUOTENAME(case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end),\n\t\t\t[file_logical_name], [file_location], dv.disk_volume, [size_on_disk_bytes],\n\t\t\t[file_type] = case when right(file_location,3) = 'ldf' then 'LOG' else 'DATA' end,\n\n\t\t\t[total_reads_writes] = [num_of_reads] + [num_of_writes], \n\t\t\t[num_of_bytes_read], [num_of_bytes_written], \n\t\t\t[total_reads_writes_bytes] = [num_of_bytes_read]+[num_of_bytes_written],\n\t\t\t\n\t\t\t[reads_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[writes_pcnt] = convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end),\n\t\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_read]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)) + ' / ' + convert(varchar,convert(numeric(20,2),case when [num_of_bytes_read] = 0 and [num_of_bytes_written] = 0 then 0\n\t\t\t\t\t\t\t\telse 100.0 * ([num_of_bytes_written]*1.0)/([num_of_bytes_read]+[num_of_bytes_written]) end)),\n\n\t\t\t--[num_of_reads], [io_stall_read_ms], [num_of_writes],  [io_stall_write_ms],\n\t\t\t--[io_stall], [io_pending_ms_ticks_total],\n\t\t\t\n\t\t\t[read_latency_ms] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else (([io_stall_read_ms] * 1.0)/[num_of_reads]) end),\n\t\t\t[write_latency_ms] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else (([io_stall_write_ms] * 1.0)/[num_of_writes]) end),\n\t\t\t[latency_ms] = convert(numeric(20,2), case when [num_of_reads] + [num_of_writes] = 0 then 0 else (([io_stall] * 1.0) / ([num_of_reads] + [num_of_writes])) end),\n\n\t\t\t[avg_bytes_per_read] = convert(numeric(20,2), case when [num_of_reads] = 0 then 0 else ( ([num_of_bytes_read] * 1.0) / [num_of_reads] ) end),\n\t\t\t[avg_bytes_per_write] = convert(numeric(20,2), case when [num_of_writes] = 0 then 0 else ( ([num_of_bytes_written] * 1.0) / [num_of_writes] ) end),\n\t\t\t[avg_bytes_per_transfer] = convert(numeric(20,2), case when [num_of_reads] = 0 and [num_of_writes] = 0 then 0 else ( (([num_of_bytes_read]+[num_of_bytes_written]) * 1.0) / ([num_of_reads]+[num_of_writes]) ) end)\n\tFROM [DiffStats] fis\n\tCROSS APPLY (\n\t\t\tselect top 1 dd.*\n\t\t\tfrom [t_DiskDrives] dd\n\t\t\twhere fis.file_location like (dd.disk_volume+'%')\n\t\t\torder by len(dd.disk_volume) desc\n\t\t) dv\n)\nselect\t[running_query] = max(running_query),\n\t\t--[collection_time_utc] = max(collection_time_utc),\n\t\t[sample_ms] = max(sample_ms),\n\t\t[database_count] = count(distinct database_name),\n\t\t[files_count] = count(*),\n\t\t[disk_volume] = max(dd.disk_volume), \n\t\t[capacity_mb] = max(dd.capacity_mb), \n\t\t[free_mb] = max(dd.free_mb),\n\t\t[db_files_size_on_disk_mb] = convert(numeric(20,2),sum(size_on_disk_bytes/1024.0/1024)),\n\t\t[total_reads_writes] = sum(total_reads_writes),\n\t\t[reads_mb] = convert(numeric(20,2),sum(num_of_bytes_read/1024.0/1024)),\n\t\t[writes_mb] = convert(numeric(20,2),sum(num_of_bytes_written/1024.0/1024)),\n\t\t[reads_writes_mb] = convert(numeric(20,2),sum( (num_of_bytes_read+num_of_bytes_written)/1024.0/1024 )),\n\t\t[pcnt_reads_writes] = convert(varchar,convert(numeric(20,2),(sum(num_of_bytes_read)*100.0/sum(num_of_bytes_read+num_of_bytes_written)))) \n\t\t\t\t\t\t\t\t+ ' / ' + \n\t\t\t\t\t\t\t\tconvert(varchar,convert(numeric(20,2),(sum(num_of_bytes_written)*100.0/sum(num_of_bytes_read+num_of_bytes_written))))\nfrom [t_FileIO] fio\nleft join [t_DiskDrives] dd on dd.disk_volume = fio.disk_volume\ngroup by dd.disk_volume\norder by [reads_writes_mb] desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @disk_drive, @database;"
      }
     ]
    }
   ]
  }
 ]
}